apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis

---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-counter
spec:
  selector:
    matchLabels:
      app: express-counter
  replicas: 2
  template:
    metadata:
      labels:
        app: express-counter
    spec:
      containers:
      - name: express-counter
        image: talreg/express-counter
